apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jithinpnjm/ds-gitops.git
    targetRevision: main
    path: apps/gateway

  destination:
    server: https://kubernetes.default.svc
    namespace: networking

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
