apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 24.x.x
    helm:
      values: |
        # 1. Admin Credentials
        auth:
          adminUser: admin
          adminPassword: "Password123!"

        # 2. External Database Configuration (Pointing to Sidecar)
        postgresql:
          enabled: false  # Disable the built-in DB
        
        externalDatabase:
          host: "127.0.0.1"
          port: 5432
          user: "vikunja-cloudsql@jithin-gcp-1234.iam"
          password: "empty"  # Proxy handles the auth!
          database: "keycloak"

        # 3. Expose via ClusterIP (Gateway handles Ingress)
        service:
          type: ClusterIP
          ports:
            http: 80
        
        # 4. Proxy/URL Settings
        proxy: edge
        httpRelativePath: "/auth/"

        # 5. SECURITY CONTEXT (Required for Bitnami + Sidecars)
        containerSecurityContext:
          runAsUser: 1001
          runAsNonRoot: true

        # 6. SERVICE ACCOUNT (Reuse the Vikunja Identity!)
        serviceAccount:
          create: true
          name: keycloak-sa
          annotations:
            iam.gke.io/gcp-service-account: vikunja-cloudsql@jithin-gcp-1234.iam.gserviceaccount.com

        # 7. THE SIDECAR (Cloud SQL Proxy)
        sidecars:
          - name: cloud-sql-proxy
            image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
            args:
              - "--private-ip"
              - "--address=127.0.0.1"
              - "--port=5432"
              - "--auto-iam-authn" # The Magic Flag
              - "jithin-gcp-1234:us-central1:vikunja-production-db"
            securityContext:
              runAsNonRoot: true
            resources:
              requests:
                cpu: "50m"
                memory: "64Mi"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true