apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 24.x.x
    helm:
      values: |
        global:
          security:
            allowInsecureImages: true

        image:
          registry: docker.io
          repository: bitnamilegacy/keycloak
          tag: "26.3.3-debian-12-r0"
          pullPolicy: IfNotPresent

        auth:
          adminUser: admin
          adminPassword: "Password123!"

        # --- FIX: OVERRIDE CACHE SETTINGS ---
        extraEnvVars:
          - name: KC_CACHE
            value: "ispn"
          - name: KC_CACHE_STACK
            value: "kubernetes"
          - name: KC_PROXY
            value: "edge"
        # ------------------------------------

        service:
          type: ClusterIP
          ports:
            http: 80

        proxy: edge
        httpRelativePath: "/auth/"

        postgresql:
          enabled: false

        externalDatabase:
          host: "127.0.0.1"
          port: 5432
          user: "vikunja-cloudsql@jithin-gcp-1234.iam"
          password: "dummy-password"
          database: "keycloak"

        podSecurityContext:
          fsGroup: 1001

        containerSecurityContext:
          runAsUser: 1001
          runAsNonRoot: true

        serviceAccount:
          create: true
          name: keycloak-sa
          annotations:
            iam.gke.io/gcp-service-account: vikunja-cloudsql@jithin-gcp-1234.iam.gserviceaccount.com

        sidecars:
          - name: cloud-sql-proxy
            image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
            args:
              - "--private-ip"
              - "--address=127.0.0.1"
              - "--port=5432"
              - "--auto-iam-authn"
              - "jithin-gcp-1234:us-central1:vikunja-production-db"
            securityContext:
              runAsNonRoot: true
            resources:
              requests:
                cpu: "50m"
                memory: "64Mi"

  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true