apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: vikunja
    jsonPointers:
    - /spec/replicas

  sources:
    - repoURL: ghcr.io/go-vikunja/helm-chart
      chart: vikunja
      targetRevision: 2.x.x
      helm:
        valueFiles:
          - $values/apps/vikunja/values.yaml

    - repoURL: https://github.com/jithinpnjm/ds-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: vikunja

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
